apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-services
  labels:
    framework: java
    tiername: AuthenticationServices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-financial
      run: authentication-services
  template:
    metadata:
      labels:
        app: ad-financial
        run: authentication-services
    spec:
      serviceAccountName: appd-app-services
      containers:
        - name: authentication-services
          image: public.ecr.aws/w3n5a5m8/adfinmod_java_services_post:latest
          envFrom:
            - configMapRef:
                name: appd-app-config          
          env:
            - name: HOST_NAME
              value: "authentication-services"
            - name: GRAPH_FILE
              value: /app-graph.json
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: AuthenticationServices              
            - name: ADWRKSHP_TIER_SRVC_NAME
              value: AuthenticationServices
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
              value: "true"
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
              value: AuthenticationServices_Node
            - name: ENABLE_IRP
              value: "true"

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
              
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-services
  labels:
    app: ad-financial
    run: authentication-services
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: authentication-services
---
