apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-services
  labels:
    framework: java
    tiername: BalanceServices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ad-financial
      run: balance-services
  template:
    metadata:
      labels:
        app: ad-financial
        run: balance-services
    spec:
      serviceAccountName: appd-app-services
      containers:
        - name: balance-services
          image: public.ecr.aws/w3n5a5m8/adfinmod_java_repositories_pre:latest
          envFrom:
            - configMapRef:
                name: appd-app-config
          env:
            - name: HOST_NAME
              value: "balance-services"
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: BalanceServices              
            - name: ADWRKSHP_TIER_SRVC_NAME
              value: BalanceServices
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
              value: "true"
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
              value: BalanceServices_Node
            - name: ENABLE_IRP
              value: "true"

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
              
---
apiVersion: v1
kind: Service
metadata:
  name: balance-services
  labels:
    app: ad-financial
    run: balance-services
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: balance-services
---
