apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-services
spec:
  replicas: 2
  selector:
    matchLabels:
      name: balance-services    
  template:
    metadata:
      labels:
        name: balance-services
    spec:
      serviceAccountName: appd-app-services
      initContainers:
      - name: appd-agent-repo
        image: appdynamics/java-agent:latest
        command: ["cp", "-ra", "/opt/appdynamics/.", "/opt/temp"]
        volumeMounts:
        - mountPath: /opt/temp
          name: shared-files
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: balance-services
          image: james201010/adfinmod_java_repositories_pre:latest   
          envFrom:
            - configMapRef:
                name: appd-app-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/opt/appdynamics/javaagent.jar
            - name: DEBUG_LEVEL
              value: debug
            - name: ADWRKSHP_TIER_SRVC_NAME
              valueFrom: 
                configMapKeyRef:
                  name: appd-app-config
                  key: ADWRKSHP_TIER_SRVC_NAME_BALNCSRVCS

            - name: APPDYNAMICS_AGENT_TIER_NAME
              valueFrom: 
                configMapKeyRef:
                  name: appd-app-config
                  key: ADWRKSHP_TIER_NAME_BALNCSRVCS

            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
              value: "true"

            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
              valueFrom: 
                configMapKeyRef:
                  name: appd-app-config
                  key: ADWRKSHP_NODE_PFX_BALNCSRVCS

            - name: ENABLE_IRP
              value: "true"
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/appdynamics
              name: shared-files
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: balance-services
spec:
  selector:
    name: balance-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
