apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-processing    
  template:
    metadata:
      labels:
        name: order-processing
    spec:
      serviceAccountName: appd-app-services
      initContainers:
      - name: appd-agent-repo
        image: docker.io/appdynamics/java-agent:20.8.0
        command: ["cp", "-ra", "/opt/appdynamics/.", "/opt/temp"]
        volumeMounts:
        - mountPath: /opt/temp
          name: shared-files
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: order-processing
          image: james201010/adfinmod_java_services_post:latest   
          envFrom:
            - configMapRef:
                name: appd-app-config
          env:
            - name: GRAPH_FILE
              value: /app-graph.json
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/opt/appdynamics/javaagent.jar
            - name: DEBUG_LEVEL
              value: debug
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: OrderProcessing
            - name: APPDYNAMICS_AGENT_NODE_NAME
              value: OrderProcessing-Node-1
            - name: ENABLE_IRP
              value: "true"
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/appdynamics
              name: shared-files
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: order-processing
spec:
  selector:
    name: order-processing
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
