apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front-end
  labels:
    framework: java
    tiername: WebFrontEnd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ad-financial
      run: web-front-end
  template:
    metadata:
      labels:
        app: ad-financial
        run: web-front-end
    spec:
      serviceAccountName: appd-app-services
      containers:
        - name: web-front-end
          image: public.ecr.aws/w3n5a5m8/adfinmod_java_webapps_pre:latest
          envFrom:
            - configMapRef:
                name: appd-app-config
          env:
            - name: HOST_NAME
              value: "web-front-end"
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: WebFrontEnd              
            - name: ADWRKSHP_TIER_SRVC_NAME
              value: WebFrontEnd
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
              value: "true"
            - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
              value: WebFrontEnd_Node
            - name: ENABLE_IRP
              value: "true"

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
              
---
apiVersion: v1
kind: Service
metadata:
  name: web-front-end
  labels:
    app: ad-financial
    run: web-front-end
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: web-front-end
---
